import { skipPreparation } from './helpers.ts';
import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
await mkdir('test-results/visual', { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('http://127.0.0.1:4173');
await page.getByRole('button', { name: 'Let’s create!' }).click();
await skipPreparation(page);
await page.screenshot({ path: 'test-results/visual/desktop.png', fullPage: true });
await page.getByRole('button', { name: '☆ Customers', exact: true }).click();
await skipPreparation(page);
await page.getByRole('button', { name: 'Color all five', exact: true }).click();
await page.getByRole('button', { name: 'Edit nail 3', exact: true }).click();
await page.screenshot({ path: 'test-results/visual/paint.png', fullPage: true });
await page.setViewportSize({ width: 768, height: 1024 });
await page.screenshot({ path: 'test-results/visual/tablet.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'test-results/visual/phone.png', fullPage: true });
console.log(JSON.stringify({ errors }));
await browser.close();
